idle:
  texture: "/DuckGame-YellowDuck.png"
  rects:
    - x: 1
      y: 11
      w: 32
      h: 32
  offset_right_x: 0
  offset_left_x: 0
  offset_y: 0
  scale_width: 0
  scale_height: 0

running:
  texture: "/DuckGame-YellowDuck.png"
  rects:
    - x: 1
      y: 11
      w: 32
      h: 32
    - x: 33
      y: 11
      w: 32
      h: 32
    - x: 66
      y: 11
      w: 32
      h: 32
    - x: 99
      y: 11
      w: 32
      h: 32
    - x: 99
      y: 11
      w: 32
      h: 32
    - x: 132
      y: 11
      w: 32
      h: 32
  offset_right_x: 0
  offset_left_x: 0
  offset_y: 0
  scale_width: 0
  scale_height: 0

crouching:
  texture: "/DuckGame-YellowDuck.png"
  rects:
    - x: 161
      y: 43
      w: 32
      h: 32
  offset_right_x: 0
  offset_left_x: 0
  offset_y: 0
  scale_width: 0
  scale_height: 0

jumping:
  texture: "/DuckGame-YellowDuck.png"
  rects:
    - x: 1
      y: 43
      w: 32
      h: 32
    - x: 33
      y: 43
      w: 32
      h: 32
    - x: 66
      y: 43
      w: 32
      h: 32
    - x: 99
      y: 43
      w: 32
      h: 32
    - x: 99
      y: 43
      w: 32
      h: 32
    - x: 1
      y: 11
      w: 32
      h: 32
  offset_right_x: 0
  offset_left_x: 0
  offset_y: 0
  scale_width: 0
  scale_height: 0

falling:
  texture: "/DuckGame-YellowDuck.png"
  rects:
    - x: 99
      y: 43
      w: 32
      h: 32
  offset_right_x: 0
  offset_left_x: 0
  offset_y: 0
  scale_width: 0
  scale_height: 0

wings_weapon:
  texture: "/DuckGame-YellowDuck.png"
  rects:
    - x: 1
      y: 566
      w: 16
      h: 16
    - x: 17
      y: 566
      w: 16
      h: 16
    - x: 33
      y: 566
      w: 16
      h: 16
    - x: 49
      y: 566
      w: 16
      h: 16
    - x: 65
      y: 566
      w: 16
      h: 16
    - x: 81
      y: 566
      w: 16
      h: 16
  offset_right_x: 12
  offset_left_x: 16
  offset_y: 15
  scale_width: 10
  scale_height: 10

dead:
  texture: "/DuckGame-YellowDuck.png"
  rects:
    - x: 1
      y: 139
      w: 32
      h: 32
    - x: 33
      y: 139
      w: 32
      h: 32
    - x: 65
      y: 139
      w: 32
      h: 32
    - x: 97
      y: 139
      w: 32
      h: 32
    - x: 129
      y: 139
      w: 32
      h: 32
    - x: 161
      y: 139
      w: 32
      h: 32
    - x: 1
      y: 171
      w: 32
      h: 32
    - x: 33
      y: 171
      w: 32
      h: 32
  offset_right_x: 0
  offset_left_x: 0
  offset_y: 0
  scale_width: 0
  scale_height: 0